# Generated by Django 5.2.17 on 2026-09-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_academicsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_year', models.CharField(choices=[('FIRST_YEAR', 'First Year'), ('SECOND_YEAR', 'Second Year'), ('THIRD_YEAR', 'Third Year'), ('FOURTH_YEAR', 'Fourth Year')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='organizations.academicsession')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'department', 'academic_session', 'study_year', 'name'), name='unique_section_per_academic_context')],
            },
        ),
    ]
